.\" Process this file with
.\" groff -man -Tascii dfmon.1
.\"
.TH DFMON 1 "dfmon"
.
.
.SH NAME
.
dfmon \- monitor disk usage
.
.
.\" -----------------------------------------------------------------
.
.SH SYNOPSIS
.
.B dfmon [-l] [-v] [-a] [-r] [-V] [-i NUM | -p PCT] [MOUNTPOINT]
.
.\" -----------------------------------------------------------------
.
.SH DESCRIPTION
.
.B dfmon
runs
.B df(1)
and compares the output for each local mount point to the previously obtained
output.
.
.\" -----------------------------------------------------------------
.
.SH OPTIONS
.
.TP
.B -l
List the most recently obtained data (percentage and mount point) and exit.
.
.TP
.BI -p PCT
Set the percent threshold of
.I MOUNTPOINT
to
.IR PCT .
.
.TP
.BI -i NUM
Set the increase threshold of
.I MOUNTPOINT
to
.IR NUM .
.
.TP
.B -v
Be verbose
.
.TP
.B -a
Check usage on all local filesystems, not just ones with a disk device node.
.
.TP
.B -r
Don't compare to the previous output.  This "resets" the monitor without
deleting any historical data.
.
.TP
.B -V
Show version information and exit.
.
.\" -----------------------------------------------------------------
.
.SH FILES
.
All data is contained within the 
.I HOST
directory in the
.B dfmon
root directory
.BR /var/local/dfmon .
The usage for each mount point is recorded in
.IR MOUNTPOINT /dfmon.log
within the
.I HOST
directory.
.P
For example, the file
.B /var/local/dfmon/gandalf/usr/dfmon.log
would contain the disk usage record for mount point
.B /usr
on host
.BR gandalf .
.P
The directory
.B dfmon.conf
within
.BI /var/local/dfmon/ MOUNTPOINT
may contain three files with special significance:
.B skip
causes
.B dfmon
to skip on a mount point;
.B threshold.percent
denotes a percentage of space used that triggers a warning, and
.B threshold.increase
denotes an
.B increase
in the percentage of space that will trigger a warning.  Warnings are printed
to standard error.
.
.\" -----------------------------------------------------------------
.
.\" .SH DIAGNOSTICS
.SH VERSION 
__VERSION__
.
.SH AUTHOR
__AUTHOR__
.
.SH COPYRIGHT
__COPYRIGHT__
.P
Released under the terms of the GNU
General Public License, version 2 -- see the file LICENSE for details.
.
.\" .SH "SEE ALSO"
.\" .BR bar (1),

